apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual2
  labels:
    creation_method: manual
    env: prod
spec:
  containers:
    - image: pruthviraj1543/kubia2
      name: kubia
      ports:
        - containerPort: 8082 
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 8080
