apiVersion: v1
kind: Pod
metadata:
  name: fortune-env-from-configmap
spec:
  containers:
  - name: fortune-container
    image: luksa/fortune:env
    env:
    - name: INTERNAL
      valueFrom:
        configMapKeyRef:
          name: fortune-config
          key: sleep-interval

